# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e2ef5aa12e78324f279b71b2b2ec5a0b30200e3ac23fb9aad3a6efc1e7266d5b832b2055eac390ac9fb61aa433b20afe9785fb97778c48cc139e34337ec01fb

test:
  secret_key_base: 5eb47108f80d36999c8de2398bc425d296d92b21d5b2fabb86cca221774ff470efc11c2c8187e128149240287b5694151251996c72e5d9770beed127b6590436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
